### ISSUE TITLE
Implement layer API and refactor positioned behavior (3)

### ISSUE THREAD

**Issue by carlosescri** [doofinder/webcomponents#56]
Depends on #63 

- [ ] The target element is not expanded when the viewport height increases; it's only contracted if the viewport height is reduced.
- [ ] Review this CSS from the classic demo:

```css
/*
  Missing:

  - z-index
  - default width / responsive width?
  - default height
  - width 100% doesn't work
 */
.df-layer-dialog {
  z-index: 1000;
  width: 100% !important; /* positioner puts nosense width!!! */
  max-width: 1140px;
  /* … */
}
```
